### PR TITLE
add mkbibquote support

### PR DESCRIPTION
**Pull request by retorquere**
mkbibquote support per #56

### CODE REVIEW

**Comment by johanneswilm** [comment]
@retorquere to see how the test output changes, temporarily uncomment this line in test/fixures-import.js:
`//  fs.writeFileSync(expected, JSON.stringify(found, null, 2))`

**Comment by retorquere** [comment]
I must have done something wrong -- I get (a.o.) this change against master for the saved match files:

```
diff --git a/test/fixtures/import/Better BibLaTeX import improvements #549.json b/test/fixtures/import/Better BibLaTeX import improvements #549.json
index 2f82237..2f94769 100644
--- a/test/fixtures/import/Better BibLaTeX import improvements #549.json        
+++ b/test/fixtures/import/Better BibLaTeX import improvements #549.json        
@@ -91,7 +91,23 @@
           },
           {
             "type": "text",
-            "text": " and mkbibquote."
+            "text": " and "
+          },
+          {
+            "type": "text",
+            "text": "mkbibquote",
+            "marks": [
+              {
+                "type": "nocase"
+              },
+              {
+                "type": "enquote"
+              }
+            ]
+          },
+          {
+            "type": "text",
+            "text": "."
           }
         ]
       },
```

and it shouldn't have generated the "nocase".

**Comment by johanneswilm** [comment]
@retorquere The nocase seems correct. In the code it links to this page: http://tex.stackexchange.com/questions/276943/biblatex-how-to-emphasize-but-not-caps-protect

**Comment by retorquere** [comment]
I had forgotten about that oddity.

**Comment by retorquere** [comment]
Alright, that passes the tests. Is this OK to merge?

**Pull request merged**
