### PR TITLE
Uglify

### PR DESCRIPTION
**Pull request by johanneswilm**
@retorquere I saw you did a bunch of things in the last few days. I couldn't stop thinking of this, so I quickly did the minifying and splitting. We are still at 406kb for the entire bundle. I won't be doing more with this, but maybe you have some ideas?

### CODE REVIEW

**Comment by retorquere** [comment]
I dunno -- I'm not sure what the benefits currently are of the split, so it's hard for me to think of things that would make the current split better.

The tests currently fail, BTW.

**Comment by johanneswilm** [comment]
I'm trying to fix the test. Then I'll merge. Well, we are down from a 1.1MB file to a 406kb file. And if one only needs one of the three converters it will be even smaller.

But 406kb is still not small. I think the edtf part may be made smaller if we for example could strip out all ```assert*``` statements. But this would require for asserts to only be used in tests. I don't think that is what edtf currently does.

**Comment by retorquere** [comment]
It would be possible to replace the asserts with no-ops with something like [grasp](http://www.graspjs.com/) in the pre-uglify bundle, but it will take some care to do this right. There's stuff like `if (cond) assert(something)` in the edtf source, so if you just strip the `assert` calls you'd get very weird behavior. replacing it with `true` should be safe I think.

**Comment by retorquere** [comment]
Is the shrinking the result of the split though? I'd have thought it would have been due to uglify.

**Comment by johanneswilm** [comment]
@retorquere Both -- uglify does most of it, but splitting it also means that each package is smaller than the entire thing. But I made it to provide both a non-split package and a split package.

btw -- I had to switch testing framework and upgrade node to newest version for it to work. I installed that node version using nvm locally. I tried with several testing frameworks and nothing quite worked.

**Comment by johanneswilm** [comment]
@retorquere ok, I'm back to holidays. Somehow the size of the JS bundles magically decreased quite a bit. I don't quite know why. The .babelrc file seems to still contain the same requirements.

You are of course welcome to change things around and switch back to nyc/ava if you manage to get that working.

**Pull request merged**
