### PR TITLE
1.3.34

### PR DESCRIPTION
**Pull request by johanneswilm**

### CODE REVIEW

**Comment by johanneswilm** [comment]
@retorquere It seems like travis builds are no longer happening so we don't get any versions released on npm. Did you turn that off or did it happen automatically due to GDPR?

**Comment by retorquere** [comment]
I haven't touched anything since allowing pull requests to run on Travis, and we've had Travis tests run since. I don't know what's happened.

**Comment by retorquere** [comment]
There's something strange going on on Travis I think. If I go to https://travis-ci.org/fiduswriter/biblatex-csl-converter and I hover over the calendar icon, it says the change was 16 days ago, but that the test finished 3 minutes ago at time of writing.

**Comment by johanneswilm** [comment]
Yes, I triggered that build again just now. That worked fine, but I could not trigger from neither master branch nor pull request. May have something to do with travis and github migrating to new solutions for open source. I just push to npm manually.

**Comment by retorquere** [comment]
Then I really don't know. I've taken a cursory look in the Travis setup and I don't see anything strange.

**Pull request merged**
