### PR TITLE
Add test cases for fiduswriter-citation-api-import#5

### PR DESCRIPTION
**Pull request by katrinleinweber**
See #89. I don't feel comfortable merging things myself into a code base I don't grasp. Locally, the tests fail in multiple ways but if Travis says ✅ here, I guess something about my npm setup is not up to par.

### CODE REVIEW

**Comment by retorquere** [comment]
wow, you manually went through all these dependencies? That's dedication. I usually just run 

`rm -rf node_modules && ncu -a && npm i`.

**Comment by katrinleinweber** [comment]
npm v6.0.0 here as well, but no, I did not go through any dependencies, AFAIK.

**Comment by retorquere** [comment]
(I've also switched to `yarn` for everything but `npm version` these days. npm in the past year has given me tons of weirdness on dependency locking, and I'm not the only one)

**Comment by retorquere** [comment]
Hey, how did you get rid of the squiggles then? After running `ncu -a` I'm seeing e.g. `"xtend": "~3.0.0"` in my package-lock.json instead of the `"xtend": "3.0.0"` you checked in. I'm also seeing `"json-schema-traverse": "0.3.1"` in your checkin, and locally after my `rm -rf ` spiel, I'm seeing `"json-schema-traverse": "^0.3.0"`. Odd.

**Comment by retorquere** [comment]
Ah, yes, that was you. Still don't know how that happened though. I do the same and I'm not getting those numbers.

**Comment by johanneswilm** [comment]
It seems that no new tests were added in this. Please reopen if I misunderstood.

**Pull request closed without merging**
